import type {
  Collection,
  GeneratedImage,
  HistoryEntry,
  ModelDef,
  PromptTemplate,
  WorkflowDef,
} from './types';

export const PROMPT_TEMPLATES: PromptTemplate[] = [
  {
    id: 't1',
    label: 'Cinematic Portrait',
    category: 'Portrait',
    prompt:
      'cinematic portrait of a woman, soft rim lighting, shallow depth of field, 85mm lens, golden hour, ultra detailed skin texture, photorealistic',
  },
  {
    id: 't2',
    label: 'Cyberpunk City',
    category: 'Scene',
    prompt:
      'neon-soaked cyberpunk megacity at night, rain-slick streets, towering holograms, volumetric fog, cinematic wide shot, blade runner aesthetic',
  },
  {
    id: 't3',
    label: 'Fantasy Landscape',
    category: 'Scene',
    prompt:
      'epic fantasy landscape, floating islands above misty valleys, cascading waterfalls, dramatic god rays, matte painting, studio ghibli inspired',
  },
  {
    id: 't4',
    label: 'Product Shot',
    category: 'Product',
    prompt:
      'studio product photography of a glass perfume bottle, seamless gradient background, soft box lighting, macro detail, commercial quality',
  },
  {
    id: 't5',
    label: 'Abstract Art',
    category: 'Abstract',
    prompt:
      'fluid abstract composition, iridescent metallic textures, flowing organic shapes, dark background, octane render, 8k',
  },
  {
    id: 't6',
    label: 'Anime Character',
    category: 'Anime',
    prompt:
      'anime key visual of a swordsman, dynamic pose, detailed eyes, cel shading, vibrant colors, makoto shinkai style',
  },
];

export const FAVORITE_PROMPTS = [
  'ethereal forest spirit, bioluminescent flora, mystical atmosphere, trending on artstation',
  'minimalist architecture, concrete and glass, brutalist, moody overcast light',
  'underwater coral reef city, bioluminescent creatures, cinematic, hyperreal',
];

export const SAMPLE_IMAGES: GeneratedImage[] = [
  {
    id: 'img-1',
    url: 'https://images.pexels.com/photos/206359/pexels-photo-206359.jpeg?auto=compress&cs=tinysrgb&w=900',
    prompt:
      'cinematic portrait of a woman, soft rim lighting, shallow depth of field, 85mm lens, golden hour, photorealistic',
    model: 'Lumen-XL v2.1',
    width: 1024,
    height: 1024,
    steps: 30,
    cfgScale: 7,
    sampler: 'DPM++ 2M Karras',
    seed: 8421039,
    createdAt: '2026-08-02T14:22:00Z',
    favorite: true,
    collectionId: 'c1',
    status: 'complete',
  },
  {
    id: 'img-2',
    url: 'https://images.pexels.com/photos/2156881/pexels-photo-2156881.jpeg?auto=compress&cs=tinysrgb&w=900',
    prompt:
      'neon-soaked cyberpunk megacity at night, rain-slick streets, towering holograms, volumetric fog',
    model: 'Lumen-XL v2.1',
    width: 1024,
    height: 1536,
    steps: 28,
    cfgScale: 6.5,
    sampler: 'Euler a',
    seed: 3192048,
    createdAt: '2026-08-02T13:10:00Z',
    favorite: false,
    status: 'complete',
  },
  {
    id: 'img-3',
    url: 'https://images.pexels.com/photos/1671325/pexels-photo-1671325.jpeg?auto=compress&cs=tinysrgb&w=900',
    prompt:
      'epic fantasy landscape, floating islands above misty valleys, cascading waterfalls, dramatic god rays',
    model: 'DreamShaper v8',
    width: 1536,
    height: 1024,
    steps: 35,
    cfgScale: 8,
    sampler: 'DPM++ 2M Karras',
    seed: 7719302,
    createdAt: '2026-08-01T22:45:00Z',
    favorite: true,
    collectionId: 'c2',
    status: 'complete',
  },
  {
    id: 'img-4',
    url: 'https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg?auto=compress&cs=tinysrgb&w=900',
    prompt:
      'studio product photography of a glass perfume bottle, seamless gradient background, soft box lighting',
    model: 'Lumen-XL v2.1',
    width: 1024,
    height: 1024,
    steps: 25,
    cfgScale: 5,
    sampler: 'DPM++ SDE Karras',
    seed: 5520101,
    createdAt: '2026-08-01T18:30:00Z',
    favorite: false,
    status: 'complete',
  },
  {
    id: 'img-5',
    url: 'https://images.pexels.com/photos/2387873/pexels-photo-2387873.jpeg?auto=compress&cs=tinysrgb&w=900',
    prompt:
      'anime key visual of a swordsman, dynamic pose, detailed eyes, cel shading, vibrant colors',
    model: 'AnythingV5',
    width: 832,
    height: 1216,
    steps: 28,
    cfgScale: 7,
    sampler: 'Euler a',
    seed: 2099441,
    createdAt: '2026-08-01T12:05:00Z',
    favorite: false,
    status: 'complete',
  },
  {
    id: 'img-6',
    url: 'https://images.pexels.com/photos/325185/pexels-photo-325185.jpeg?auto=compress&cs=tinysrgb&w=900',
    prompt:
      'minimalist architecture, concrete and glass, brutalist, moody overcast light',
    model: 'DreamShaper v8',
    width: 1536,
    height: 1024,
    steps: 30,
    cfgScale: 7,
    sampler: 'DPM++ 2M Karras',
    seed: 6647128,
    createdAt: '2026-07-31T20:15:00Z',
    favorite: true,
    status: 'complete',
  },
  {
    id: 'img-7',
    url: 'https://images.pexels.com/photos/1271619/pexels-photo-1271619.jpeg?auto=compress&cs=tinysrgb&w=900',
    prompt:
      'underwater coral reef city, bioluminescent creatures, cinematic, hyperreal',
    model: 'Lumen-XL v2.1',
    width: 1024,
    height: 1024,
    steps: 32,
    cfgScale: 7.5,
    sampler: 'DPM++ 2M Karras',
    seed: 9981200,
    createdAt: '2026-07-31T09:40:00Z',
    favorite: false,
    status: 'complete',
  },
  {
    id: 'img-8',
    url: 'https://images.pexels.com/photos/3573554/pexels-photo-3573554.jpeg?auto=compress&cs=tinysrgb&w=900',
    prompt:
      'fluid abstract composition, iridescent metallic textures, flowing organic shapes, dark background, octane render',
    model: 'Lumen-XL v2.1',
    width: 1024,
    height: 1024,
    steps: 30,
    cfgScale: 6,
    sampler: 'Euler a',
    seed: 4455812,
    createdAt: '2026-07-30T16:20:00Z',
    favorite: false,
    status: 'complete',
  },
  {
    id: 'img-9',
    url: 'https://images.pexels.com/photos/3052361/pexels-photo-3052361.jpeg?auto=compress&cs=tinysrgb&w=900',
    prompt:
      'ethereal forest spirit, bioluminescent flora, mystical atmosphere, trending on artstation',
    model: 'DreamShaper v8',
    width: 832,
    height: 1216,
    steps: 35,
    cfgScale: 8,
    sampler: 'DPM++ SDE Karras',
    seed: 1120938,
    createdAt: '2026-07-30T11:00:00Z',
    favorite: true,
    collectionId: 'c2',
    status: 'complete',
  },
  {
    id: 'img-10',
    url: 'https://images.pexels.com/photos/1693650/pexels-photo-1693650.jpeg?auto=compress&cs=tinysrgb&w=900',
    prompt:
      'retro-futuristic spaceship interior, warm amber lighting, control panels, sci-fi concept art',
    model: 'Lumen-XL v2.1',
    width: 1536,
    height: 1024,
    steps: 30,
    cfgScale: 7,
    sampler: 'DPM++ 2M Karras',
    seed: 7300192,
    createdAt: '2026-07-29T19:50:00Z',
    favorite: false,
    status: 'complete',
  },
  {
    id: 'img-11',
    url: 'https://images.pexels.com/photos/1366919/pexels-photo-1366919.jpeg?auto=compress&cs=tinysrgb&w=900',
    prompt:
      'macro photography of a dewdrop on a leaf, morning mist, bokeh background, ultra sharp',
    model: 'Lumen-XL v2.1',
    width: 1024,
    height: 1024,
    steps: 28,
    cfgScale: 6,
    sampler: 'DPM++ SDE Karras',
    seed: 5592103,
    createdAt: '2026-07-29T08:15:00Z',
    favorite: false,
    status: 'complete',
  },
  {
    id: 'img-12',
    url: 'https://images.pexels.com/photos/2387873/pexels-photo-2387873.jpeg?auto=compress&cs=tinysrgb&w=900',
    prompt:
      'character concept sheet, armored knight, multiple angles, turnaround, clean background',
    model: 'AnythingV5',
    width: 1024,
    height: 1536,
    steps: 32,
    cfgScale: 7,
    sampler: 'Euler a',
    seed: 8810234,
    createdAt: '2026-07-28T22:30:00Z',
    favorite: false,
    status: 'complete',
  },
];

export const COLLECTIONS: Collection[] = [
  {
    id: 'c1',
    name: 'Portraits',
    description: 'Character studies and cinematic portraits',
    coverUrl: SAMPLE_IMAGES[0].url,
    count: 24,
    createdAt: '2026-07-15T10:00:00Z',
  },
  {
    id: 'c2',
    name: 'Fantasy Worlds',
    description: 'Landscapes and ethereal environments',
    coverUrl: SAMPLE_IMAGES[2].url,
    count: 47,
    createdAt: '2026-07-10T10:00:00Z',
  },
  {
    id: 'c3',
    name: 'Product Shots',
    description: 'Commercial product photography renders',
    coverUrl: SAMPLE_IMAGES[3].url,
    count: 18,
    createdAt: '2026-07-20T10:00:00Z',
  },
  {
    id: 'c4',
    name: 'Experiments',
    description: 'Abstract and exploratory compositions',
    coverUrl: SAMPLE_IMAGES[7].url,
    count: 31,
    createdAt: '2026-07-05T10:00:00Z',
  },
];

export const WORKFLOWS: WorkflowDef[] = [
  {
    id: 'w1',
    name: 'SDXL Text-to-Image',
    description: 'Standard high-quality text-to-image pipeline with refiner',
    nodes: 12,
    category: 'Text-to-Image',
    updatedAt: '2026-07-28T10:00:00Z',
    active: true,
  },
  {
    id: 'w2',
    name: 'Img2Img Refine',
    description: 'Upload an image and refine it with a text prompt',
    nodes: 9,
    category: 'Image-to-Image',
    updatedAt: '2026-07-25T10:00:00Z',
    active: true,
  },
  {
    id: 'w3',
    name: 'Upscale 4x',
    description: 'Latent upscale with ControlNet tile for 4x resolution',
    nodes: 15,
    category: 'Upscale',
    updatedAt: '2026-07-22T10:00:00Z',
    active: false,
  },
  {
    id: 'w4',
    name: 'Batch Variations',
    description: 'Generate variations from a seed with prompt interpolation',
    nodes: 8,
    category: 'Batch',
    updatedAt: '2026-07-18T10:00:00Z',
    active: true,
  },
  {
    id: 'w5',
    name: 'Inpaint Mask',
    description: 'Masked inpainting with region-specific prompts',
    nodes: 14,
    category: 'Inpaint',
    updatedAt: '2026-07-12T10:00:00Z',
    active: false,
  },
];

export const MODELS: ModelDef[] = [
  {
    id: 'm1',
    name: 'Lumen-XL v2.1',
    base: 'SDXL',
    type: 'checkpoint',
    size: '6.5 GB',
    downloads: 184200,
    likes: 12400,
    tags: ['photoreal', 'cinematic', 'versatile'],
    updatedAt: '2026-07-30T10:00:00Z',
  },
  {
    id: 'm2',
    name: 'DreamShaper v8',
    base: 'SD 1.5',
    type: 'checkpoint',
    size: '2.1 GB',
    downloads: 98200,
    likes: 8900,
    tags: ['artistic', 'fantasy', 'painterly'],
    updatedAt: '2026-07-26T10:00:00Z',
  },
  {
    id: 'm3',
    name: 'AnythingV5',
    base: 'SD 1.5',
    type: 'checkpoint',
    size: '2.1 GB',
    downloads: 76400,
    likes: 6200,
    tags: ['anime', 'illustration', 'cel-shaded'],
    updatedAt: '2026-07-24T10:00:00Z',
  },
  {
    id: 'm4',
    name: 'Detail Enhancer LoRA',
    base: 'SDXL',
    type: 'lora',
    size: '145 MB',
    downloads: 42100,
    likes: 3100,
    tags: ['detail', 'sharpen', 'addon'],
    updatedAt: '2026-07-20T10:00:00Z',
  },
  {
    id: 'm5',
    name: 'Cinematic Lighting LoRA',
    base: 'SDXL',
    type: 'lora',
    size: '98 MB',
    downloads: 38900,
    likes: 2800,
    tags: ['lighting', 'cinematic', 'mood'],
    updatedAt: '2026-07-18T10:00:00Z',
  },
  {
    id: 'm6',
    name: 'Tile ControlNet',
    base: 'SDXL',
    type: 'controlnet',
    size: '1.4 GB',
    downloads: 22100,
    likes: 1500,
    tags: ['upscale', 'controlnet', 'tile'],
    updatedAt: '2026-07-15T10:00:00Z',
  },
];

export const HISTORY: HistoryEntry[] = [
  {
    id: 'h1',
    prompt: 'cinematic portrait of a woman, soft rim lighting, golden hour',
    model: 'Lumen-XL v2.1',
    status: 'complete',
    durationSeconds: 14,
    createdAt: '2026-08-02T14:22:00Z',
    imageId: 'img-1',
  },
  {
    id: 'h2',
    prompt: 'neon-soaked cyberpunk megacity at night, rain-slick streets',
    model: 'Lumen-XL v2.1',
    status: 'complete',
    durationSeconds: 18,
    createdAt: '2026-08-02T13:10:00Z',
    imageId: 'img-2',
  },
  {
    id: 'h3',
    prompt: 'epic fantasy landscape, floating islands, cascading waterfalls',
    model: 'DreamShaper v8',
    status: 'complete',
    durationSeconds: 22,
    createdAt: '2026-08-01T22:45:00Z',
    imageId: 'img-3',
  },
  {
    id: 'h4',
    prompt: 'studio product photography of a glass perfume bottle',
    model: 'Lumen-XL v2.1',
    status: 'failed',
    durationSeconds: 3,
    createdAt: '2026-08-01T18:20:00Z',
  },
  {
    id: 'h5',
    prompt: 'anime key visual of a swordsman, dynamic pose, cel shading',
    model: 'AnythingV5',
    status: 'complete',
    durationSeconds: 11,
    createdAt: '2026-08-01T12:05:00Z',
    imageId: 'img-5',
  },
  {
    id: 'h6',
    prompt: 'minimalist architecture, concrete and glass, brutalist',
    model: 'DreamShaper v8',
    status: 'canceled',
    durationSeconds: 5,
    createdAt: '2026-07-31T20:10:00Z',
  },
];

export const SAMPLERS = [
  'DPM++ 2M Karras',
  'DPM++ SDE Karras',
  'Euler a',
  'Euler',
  'DDIM',
  'UniPC',
];

export const ASPECT_RATIOS = [
  { label: '1:1', value: '1:1', w: 1024, h: 1024 },
  { label: '3:2', value: '3:2', w: 1536, h: 1024 },
  { label: '2:3', value: '2:3', w: 1024, h: 1536 },
  { label: '16:9', value: '16:9', w: 1536, h: 864 },
  { label: '9:16', value: '9:16', w: 864, h: 1536 },
];
